name: Matrix Strategy Sample
on: push
# The trigger to which the workflow will run 
jobs:
  example_matrix:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

#       - name: Run read-yaml matruix action
#         id: yaml-arr-data
#         uses: jbutcher5/read-yaml@main     
#         with:
#           file: './deploy.yml'         
#           key-path: '["mat"]' 
        

            
