name: Matrix Strategy Sample
on: push
# The trigger to which the workflow will run 
jobs:
  example_matrix:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          
      - name: List before delete files
        run: ls

      - name: Run read-yaml matruix action
        id: yaml-arr-data
        uses: jbutcher5/read-yaml@main     
        with:
          file: './deploy.yml'         
          key-path: '["mat"]' 
        
      - name: Display read-array-yaml output
        run: echo "${{ steps.yaml-arr-data.outputs.data }}"
      
    strategy:
      matrix:
        vals: ${{ steps.yaml-arr-data.outputs.data }}
