name: Matrix Strategy Sample
on: push
# The trigger to which the workflow will run
jobs:
  provide_packages_json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo "::set-output name=matrix::$(./deploy-json --names)"

    # here, we save the result of this 1st phase to the "outputs"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  # phase 2
  split_monorepo:
    # this means, wait for the "provide_packages_json" phase 1 to finish
    needs: provide_packages_json

    runs-on: ubuntu-latest
    strategy:
      # ↓ the real magic happens here - create dynamic matrix from the json
      matrix:
        package: ${{ fromJson(needs.provide_packages_json.outputs.matrix) }}
