name: 'example'
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  matrix_input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Run read-yaml action
        id: yaml-data
        uses: jbutcher5/read-yaml@main     
        with:
          file: './deploy.yml'         
          key-path: '["deploy"]' 

      - name: Display read-yaml output
        run: echo "${{ steps.yaml-data.outputs.data }}"
      
      - uses: danyow/json-matrix-builder@v0.5.0
        id: array
        with:
          str: ${{ steps.yaml-data.outputs.data }}
          separator: ','
    outputs:
      param: ${{ steps.array.outputs.build }}
      
  dynamic_matrix:
    needs:
      - matrix_input
    strategy:
      matrix:
        # Three matrix jobs work, builder.ts, execer.ts. main.ts
        param: ${{ fromJson(needs.matrix_input.outputs.param) }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ matrix.param }}
