name: 'example'
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  matrix_input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Run read-yaml action
        id: yaml-data
        uses: jbutcher5/read-yaml@main     
        with:
          file: './deploy.yml'         
          key-path: '["deploy"]' 

      - name: Display read-yaml output
        run: echo "${{ steps.yaml-data.outputs.data }}"
      
      - uses: danyow/json-matrix-builder@v0.5.0
        id: array
        with:
          str: ${{ steps.yaml-data.outputs.data }}
          separator: ','
    outputs:
      param: ${{ steps.array.outputs.build }}
      
  dynamic_matrix:
  
    runs-on: ubuntu-latest
    needs:
      - matrix_input
      
    strategy:
      fail-fast: false
      matrix:
        param: ${{ fromJson(needs.matrix_input.outputs.param) }}        
        node-version: [16.6]
        
    steps:
      - run: |
          echo ${{ matrix.param }}
      
      - uses: actions/checkout@v3
    
      - name: List before delete files
        run: ls
        
      - name: Rename file 
        run: mv app.module.${{ matrix.param }}.ts app.module.ts
        
      - name: List after delete files
        run: ls
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
          
      - name: Install node dependencies
        run: npm ci
      
      - name: Build the Cockpit app for ${{ matrix.param }}   
        run: npm run build --if-present
        
      - name: Deploy the Cockpit app for ${{ matrix.param }}   
        run: npm run deploy
