name: Matrix Strategy Sample
on: push
# The trigger to which the workflow will run
jobs:
  provide_packages_json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo "::set-output name=matrix::$(./deploysd-json --names)"

      - name: Run read-yaml action
        run: echo "${{ steps.set-matrix.outputs.matrix }}"
    
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

#     strategy:
#       matrix:
#         package: ${{fromJson(needs.provide_packages_json.outputs.matrix)}}
