on:
  pull_request:
  push:
    branches:
      - main
jobs:
  matrix_input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Run read-yaml action
        id: yaml-data
        uses: jbutcher5/read-yaml@main     
        with:
          file: './deploy.yml'         
          key-path: '["deploy"]' 

      - name: Display read-yaml output
        run: echo "${{ steps.yaml-data.outputs.data }}"
      
      - uses: danyow/json-matrix-builder@v0.5.0
        id: array
        with:
          str: ${{ steps.yaml-data.outputs.data }}
          separator: ','
    outputs:
      param: ${{ steps.array.outputs.build }}
      
  dynamic_matrix:
  
    runs-on: ubuntu-latest
    needs:
      - matrix_input
      
    strategy:
      fail-fast: false
      matrix:
        param: ${{ fromJson(needs.matrix_input.outputs.param) }}             
        node-version: [16.6]      
        
    steps:
      - run: |
          echo ${{ matrix.param }}
      
      - uses: actions/checkout@v3

      - name: read-yaml-file
        uses: pietrobolcato/action-read-yaml@1.0.0
        id: read_action_js
        with:
          config: ./deploy.yml
          
      - name: use-yaml-file
        run: |
          echo deploy: ${{ steps.read_action_js.outputs['deploy'] }}
          echo deploy_url=${{ steps.read_action_js.outputs['${{ matrix.param }}-url'] }} >> $GITHUB_ENV
          echo location: ${{ steps.read_action_js.outputs['${{ matrix.param }}-url'] }}
          echo default_url=${{ steps.read_action_js.outputs['default-url-url'] }} >> $GITHUB_ENV
          echo environment: ${{ steps.read_action_js.outputs['default-url'] }}
          echo env: ${{ env.deploy_url }}
          echo env2: ${{ env.default_url }}
          
#       - name: Run read-yaml action
#         id: yaml-data
#         uses: jbutcher5/read-yaml@main     
#         with:
#           file: './deploy.yml'         
#           key-path: '["${{ matrix.param }}-url"]' 
          
      - name: Run read-yaml action |
        uses: jbutcher5/read-yaml@main  
        if: |
          ${{ ! steps.read_action_js.outputs['${{ matrix.param }}-url'] == ''}}
          run: |
           echo "deploy_url=${{ steps.read_action_js.outputs['${{ matrix.param }}-url'] }}" >> $GITHUB_ENV        
             
          ${{ steps.read_action_js.outputs['${{ matrix.param }}-url']  == ''}}
          run: |
           echo "deploy_url=${{ steps.read_action_js.outputs['default-url'] }}" >> $GITHUB_ENV        
             
#       - name: Get Default URL read-yaml action
#         if: ${{ steps.yaml-data.outputs.data  == ''}}
#         id: yaml-def-data
#         uses: jbutcher5/read-yaml@main     
#         with:
#           file: './deploy.yml'         
#           key-path: '["default-url"]' 
          
#       - name: Get Default URL read-yaml action          
#         if: ${{ steps.yaml-data.outputs.data  == ''}}
#         run: |
#          echo deploy_url=${{ matrix.param }}" >> $GITHUB_ENV      
         
#       - name: Set output
#         id: url-data
#         run: echo "deploy_url=${{ matrix.param }}" >> $GITHUB_ENV
        
      - name: Use the value
        id: step_two
        run: echo "${{ env.deploy_url }}"
        
#         if: ${{ !steps.yaml-data.outputs.data  == ''}}
#            run: |
#              echo "Not Empty"
