on:
  pull_request:
  push:
    branches:
      - main
jobs:
  matrix_input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Run read-yaml action
        id: yaml-data
        uses: jbutcher5/read-yaml@main     
        with:
          file: './deploy.yml'         
          key-path: '["deploy"]' 

      - name: Display read-yaml output
        run: echo "${{ steps.yaml-data.outputs.data }}"
      
      - uses: danyow/json-matrix-builder@v0.5.0
        id: array
        with:
          str: ${{ steps.yaml-data.outputs.data }}
          separator: ','
    outputs:
      param: ${{ steps.array.outputs.build }}
      
  dynamic_matrix:
  
    runs-on: ubuntu-latest
    needs:
      - matrix_input
      
    strategy:
      fail-fast: false
      matrix:
        param: ${{ fromJson(needs.matrix_input.outputs.param) }}             
        node-version: [16.6]      
        
    steps:
      - run: |
          echo ${{ matrix.param }}
      
      - uses: actions/checkout@v3
          
      - name: Run read-yaml action
        id: yaml-data
        uses: jbutcher5/read-yaml@main     
        with:
          file: './deploy.yml'         
          key-path: '["deploy", "devtest-url"]' 
          
      - name: Run read-yaml action
        if: ${{ ! steps.yaml-data.outputs.data  == ''}}
        run: |
         echo "No Empty "  ${{ steps.yaml-data.outputs.data }}       
             
      - name: Run read-yaml action
        if: ${{ steps.yaml-data.outputs.data  == ''}}
        run: |
         echo "empty "  ${{ steps.yaml-data.outputs.data }}     
         
      - name: Set output
        id: url-data
        run: echo "deploy_url=${{ matrix.param }}" >> $GITHUB_ENV
        
      - name: Use the value
        id: step_two
        run: echo "${{ env.deploy_url }}"
        
#         if: ${{ !steps.yaml-data.outputs.data  == ''}}
#            run: |
#              echo "Not Empty"
