name: CI
on:
  push:
    branches: [ "main" ]

jobs:
    
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
    
    
      - name: Run read-yaml action
        id: yaml-data
        uses: jbutcher5/read-yaml@main     
        with:
          file: './deploy.yml'         
          key-path: '["deploy"]' 
          
      - name: Run read-yaml action
        if: ${{ ! steps.yaml-data.outputs.data  == ''}}
        run: |
         echo "Not empty"        
             
      - name: Run read-yaml action
        if: ${{ steps.yaml-data.outputs.data  == ''}}
        run: |
         echo "empty"        
         
      - name: Set output
        id: url-data
        run: echo "deploy_url=${{ steps.yaml-data.outputs.data }}" >> $GITHUB_ENV
        
      - name: Use the value
        id: step_two
        run: echo "${{ env.action_state }}"
        
#         if: ${{ !steps.yaml-data.outputs.data  == ''}}
#            run: |
#              echo "Not Empty"
