name: CI
on:
  push:
    branches: [ "main" ]

jobs:

  pre-build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
    
      - name: Run read-yaml action
        id: yaml-data
        uses: jbutcher5/read-yaml@main      # You may wish to replace main with a version tag such as '1.6' etc.
        with:
          file: './deploy.yml'          # File to read from
          key-path: '["deploy"]' # Access the runs key then the using key and retuns the value.

      - name: Display read-yaml output
        run: echo "${{ steps.yaml-data.outputs.data }}"
                
      - name: List before delete files
        run: ls
        
      - name: Delete file 
        run: rm -f app.module.ts
        
      - name: Rename file 
        run: mv app.module.${{ steps.yaml-data.outputs.data }}.ts app.module.ts
        
      - name: List after delete files
        run: ls
        
    
    
  build:
  
    needs: [pre-build]
    runs-on: ubuntu-latest

    steps:
       # Validate Property
      - name: Read value from Properties-file
        id: read_property
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: './deploy.properties'
          properties: 'deploy.env'
          
      - name: Do something with your bumped release version
        run: echo ${{ steps.read_property.outputs.the-key-of-a-property }}
        
      - name: Do something with your data
        run: echo ${{ steps.read_property.outputs.data }}
        # will print "the value of 'the.key.of.a.property'"
              
        
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
